<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net462</TargetFramework>
    <RootNamespace>Test_Application</RootNamespace>
    <AssemblyName>Test Application</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="DirectShowLib-2005">
      <HintPath>..\Source\Assemblies\DirectShowLib-2005.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Source\WPF MediaKit.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="EVRPresenter32.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="EVRPresenter64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>